name: Deploy gh-pages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    name: Deploy gh-pages
    steps:
      - name: Pull down this repo
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Pull down heimdall-lite
        run: |
          curl -s "https://api.github.com/repos/mitre/heimdall2/releases/latest" | jq -r ".tarball_url" | xargs -I{} curl {} -L -o heimdall_tar.tar.gz
          tar xvzf heimdall_tar.tar.gz --strip-components 1
          rm heimdall_zip.zip
      - name: Build heimdall-lite
        run: |
          yarn install --frozen-lockfile
          yarn frontend build
      - name: Write heimdall-lite CNAME file
        run: 'echo "heimdall-lite.cms.gov" > ./dist/frontend/CNAME'
      - name: Deploy heimdall-lite
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/frontend
